name: Deploy to Azure Container Apps

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout cod
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Login in Azure
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # 3. Login in Azure Container Registry
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: rasregistryacr.azurecr.io
        username: ${{ fromJSON(secrets.AZURE_CREDENTIALS).clientId }}
        password: ${{ fromJSON(secrets.AZURE_CREDENTIALS).clientSecret }}

    # 4. Build și push imagine Web
    - name: Build and push Web image
      run: |
        docker build -f Dockerfile.web -t rasregistryacr.azurecr.io/flask-web:latest .
        docker push rasregistryacr.azurecr.io/flask-web:latest

    # 5. Build și push imagine Worker
    - name: Build and push Worker image
      run: |
        docker build -f Dockerfile.worker -t rasregistryacr.azurecr.io/flask-worker:latest .
        docker push rasregistryacr.azurecr.io/flask-worker:latest

    # 6. Deploy Web Container App
    - name: Deploy Web Container App
      run: |
        az containerapp update \
          --name ras-expeditors-web \
          --resource-group ras_expeditors \
          --image rasregistryacr.azurecr.io/flask-web:latest \
          --env-vars FLASK_APP=app.py FLASK_ENV=production \
                     SECRET_KEY=${{ secrets.SECRET_KEY }} \
                     MYSQL_HOST=${{ secrets.MYSQL_HOST }} \
                     MYSQL_USER=${{ secrets.MYSQL_USER }} \
                     MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} \
                     MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }} \
                     CELERY_BROKER_URL=${{ secrets.REDIS_URL }} \
                     CELERY_RESULT_BACKEND=${{ secrets.REDIS_URL }}

    # 7. Deploy Worker Container App
    - name: Deploy Worker Container App
      run: |
        az containerapp update \
          --name ras-expeditors-worker \
          --resource-group ras_expeditors \
          --image rasregistryacr.azurecr.io/flask-worker:latest \
          --env-vars CELERY_BROKER_URL=${{ secrets.REDIS_URL }} \
                     CELERY_RESULT_BACKEND=${{ secrets.REDIS_URL }}
